Repository ham-study/algorithm-study, pull requests merged in 2022-01, with the labels that each got.

#9 W1D1 프로그래머스 17680
  2. programmers/hanjo/README.md
  2. programmers/hanjo/개인/temp/Solution.java
  2. programmers/hanjo/구현/카카오_2_캐시/Solution.java
Labels: 구현

#8 solve: 프로그래머스 17680
  2. programmers/seung-hun/bruteforce/keep.md
  2. programmers/seung-hun/implementation/PGMS17680.java
Labels: 구현

#6 solve: programmers 17680 캐시
  2. programmers/jihun/구현/programmers_17680_캐시.java
Labels: 구현

#10 solve : 프로그래머스 17680
  2. programmers/eonju/issue2.java
Labels: 구현

#13 unsolve/#4 : boj 12919
  1.baekjoon/jihun/boj_12919.java
Labels: 완전탐색

#14 재원: W1D2 - 실패 (#3)
  1.baekjoon/hanjo/example/Main.java
  1.baekjoon/hanjo/완전탐색_S1/Main.java
  2. programmers/hanjo/개인/temp/Solution.java
  2. programmers/hanjo/구현/카카오_2_캐시/Solution.java
Labels: 완전탐색

#11 solve: BOJ12919(#4)
  1.baekjoon/seung-hun/bruteforce/BOJ12919.java
  1.baekjoon/seung-hun/bruteforce/keep.md
  2. programmers/.keep
Labels: 완전탐색

#12 unsolved: 백준 12919
  1.baekjoon/eonju/issue4/Main.java
Labels: 완전탐색

#17 Sol #5 : boj 1260
  1.baekjoon/jihun/boj_1260.java
Labels: 그래프

#15 solve: BOJ1260
  1.baekjoon/seung-hun/graph/BOJ1260.java
Labels: 그래프

#18 unsolve: BOJ1260
  1.baekjoon/eonju/issue5/Main.java
  1.baekjoon/eonju/issue5/Node.java
Labels: 그래프

#19 fail: BOJ2504
  1.baekjoon/seung-hun/datastructure/BOJ2504.java
Labels: 자료구조

#22 unsolved: 백준 2504
  1.baekjoon/eonju/issue3/Main.java
Labels: 자료구조

#21 W1D5 - 대실패
  1.baekjoon/hanjo/example/Main.java
  1.baekjoon/hanjo/example/Main2.java
  1.baekjoon/hanjo/그래프_S2_1260/Main.java
  1.baekjoon/hanjo/완전탐색_S1/Main.java
  1.baekjoon/hanjo/완전탐색_S1_12919/Main.java
  1.baekjoon/hanjo/자료구조_S2_2504/Test.java
  1.baekjoon/hanjo/자료구조_S2_2504/Try.java
  1.baekjoon/hanjo/자료구조_S2_2504/Try2.java
Labels: 자료구조

#30 solve: 백준 11726
  1.baekjoon/eonju/issue23/Main.java
Labels: 동적계획법

#28 solve: BOJ11726 DP
  1.baekjoon/seung-hun/dp/BOJ11726.java
Labels: 동적계획법

#31 solve: PGMS42626
  1.baekjoon/seung-hun/datastructure/BOJ2504.java
  1.baekjoon/seung-hun/datastructure/PGMS42626.java
  2. programmers/seung-hun/datastructure/PGMS42626.java
Labels: 자료구조

#32 Solve : 프로그래머스 42626
  2. programmers/eonju/issue2/Solution.java
  2. programmers/eonju/issue24/Solution.java
Labels: 자료구조

#34 solve: BOJ6443
  1.baekjoon/seung-hun/bruteforce/BOJ6443.java
  1.baekjoon/seung-hun/datastructure/PGMS42626.java
Labels: 완전탐색

#36 unsolve: 프로그래머스 6443
  1.baekjoon/eonju/issue27/Main.java
Labels: 완전탐색

#38 solve: 프로그래머스 43162
  2. programmers/eonju/issue26/Solution.java
Labels: 그래프

#41 unsolve: 프로그래머스 60059
  2. programmers/eonju/issue25/Solution.java
Labels: 구현

#49 fail: BOJ2110
  1.baekjoon/seung-hun/binary-search/BOJ2110.java
Labels: 이분탐색

#50 unsolve: 프로그래머스 2110
  1.baekjoon/eonju/issue44/Main.java
  1.baekjoon/eonju/issue47/Main.java
Labels: 이분탐색

#51 W3D1 - 실패
  1.baekjoon/hanjo/이분탐색_G5_2110/Main.java
Labels: 이분탐색

#55 W3D2 - 실패
  1.baekjoon/hanjo/동적계획법_G5_9251/Main.java
  1.baekjoon/hanjo/이분탐색_G5_2110/Main.java
Labels: 동적계획법

#52 solve: BOJ9251
  1.baekjoon/seung-hun/dp/BOJ9251.java
Labels: 동적계획법

#59 W3D3 실패
  1.baekjoon/hanjo/그래프_S2_DFS와BFS/Main.java
  1.baekjoon/hanjo/동적계획법_G5_LCS/Main.java
  1.baekjoon/hanjo/완전탐색_G5_A와B2/Main.java
  1.baekjoon/hanjo/완전탐색_G5_감시/Main.java
  1.baekjoon/hanjo/이분탐색_G5_공유기설치/Main.java
  1.baekjoon/hanjo/자료구조_S2_괄호의값/Test.java
  1.baekjoon/hanjo/자료구조_S2_괄호의값/Try.java
  1.baekjoon/hanjo/자료구조_S2_괄호의값/Try2.java
Labels: 완전탐색

#58 unsove
  1.baekjoon/eonju/issue43/Main.java
Labels: 완전탐색

#57 fail: BOJ15683
  1.baekjoon/seung-hun/bruteforce/BOJ15683.java
Labels: 구현, 완전탐색

#60 sol: boj 18352
  1.baekjoon/jihun/boj_18352.java
Labels: 그래프

#61 W3D4 - 실패
  1.baekjoon/hanjo/example/Main.java
  1.baekjoon/hanjo/example/Main2.java
  1.baekjoon/hanjo/그래프_S2_특정거리도시찾기/Main.java
Labels: 그래프

#62 solve: BOJ18352
  1.baekjoon/seung-hun/bruteforce/BOJ15683.java
  1.baekjoon/seung-hun/graph/BOJ18352.java
Labels: 그래프

#63 unsolve: 백준 18352
  1.baekjoon/eonju/issue46/Main.java
Labels: 그래프

#67 unsolve: 백준 14499
  1.baekjoon/eonju/14499/Main.java
Labels: 구현

#65 W3D5 - 실패
  1.baekjoon/hanjo/구현_G4_주사위굴리기/Main.java
  1.baekjoon/hanjo/구현_G4_주사위굴리기/Try1.java
  1.baekjoon/hanjo/그래프_S2_특정거리도시찾기/Main.java
Labels: 구현

#64 solve: BOJ14499
  1.baekjoon/seung-hun/implementation/BOJ14499.java
Labels: 구현

#73 solve: BOJ1504
  1.baekjoon/seung-hun/graph/BOJ1504.java
Labels: 그래프

#75 W4D1 - 실패
  1.baekjoon/hanjo/구현_G4_주사위굴리기/Main.java
  1.baekjoon/hanjo/그래프_G4_특정한최단경로/Main.java
  1.baekjoon/hanjo/그래프_G4_특정한최단경로/Test.java
Labels: 그래프

#76 unsolve: 백준 1504
  1.baekjoon/eonju/1504/Main.java
Labels: 그래프

#79 solve: 백준 18870
  1.baekjoon/eonju/18870/Main.java
Labels: 정렬

#78 W4D2 - 성공
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/example/Main.java
  1.baekjoon/hanjo/boj/example/Main2.java
  1.baekjoon/hanjo/boj/구현_G4_주사위굴리기/Main.java
  1.baekjoon/hanjo/boj/구현_G4_주사위굴리기/Try1.java
  1.baekjoon/hanjo/boj/그래프_G4_특정한최단경로/Main.java
  1.baekjoon/hanjo/boj/그래프_G4_특정한최단경로/Test.java
  1.baekjoon/hanjo/boj/그래프_S2_DFS와BFS/Main.java
  1.baekjoon/hanjo/boj/그래프_S2_특정거리도시찾기/Main.java
  1.baekjoon/hanjo/boj/동적계획법_G5_LCS/Main.java
  1.baekjoon/hanjo/boj/완전탐색_G5_A와B2/Main.java
  1.baekjoon/hanjo/boj/완전탐색_G5_감시/Main.java
  1.baekjoon/hanjo/boj/이분탐색_G5_공유기설치/Main.java
  1.baekjoon/hanjo/boj/자료구조_S2_괄호의값/Test.java
  1.baekjoon/hanjo/boj/자료구조_S2_괄호의값/Try.java
  1.baekjoon/hanjo/boj/자료구조_S2_괄호의값/Try2.java
  1.baekjoon/hanjo/boj/정렬_S2_좌표압축/Main.java
  1.baekjoon/hanjo/programmers/자료구조_2_다리를지나는트럭/Solution.java
  1.baekjoon/hanjo/programmers/카카오_2_캐시/Solution.java
  2. programmers/hanjo/README.md
Labels: 정렬

#77 solve: BOJ18870
  1.baekjoon/seung-hun/sort/BOJ18870.java
Labels: 이분탐색, 정렬

#83 W4D3 - 실패
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/그래프_S1_효율적인해킹/Main.java
  1.baekjoon/hanjo/boj/그래프_S1_효율적인해킹/Test.java
  1.baekjoon/hanjo/boj/그래프_S1_효율적인해킹/Try.java
  1.baekjoon/hanjo/boj/그래프_S1_효율적인해킹/testcase.txt
  1.baekjoon/hanjo/boj/백트래킹_G5_NQueen/Main.java
  1.baekjoon/hanjo/boj/최단경로_G4_특정한최단경로/Main.java
  1.baekjoon/hanjo/boj/최단경로_G4_특정한최단경로/Test.java
  1.baekjoon/hanjo/boj/최단경로_S2_특정거리도시찾기/Main.java
Labels: 백트래킹

#84 unsolve: 백준 9663
  1.baekjoon/eonju/9663/Main.java
Labels: 백트래킹

#81 solve: BOJ9663 bruteforce
  1.baekjoon/seung-hun/bruteforce/BOJ9663.java
Labels: 백트래킹

#88 unsolve: 프로그래머스 43238
  2. programmers/eonju/43238/Solution.java
Labels: 이분탐색

#87 W4D4 - 실패
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/백트래킹_G5_NQueen/Main.java
  1.baekjoon/hanjo/programmers/이분탐색_3_입국심사/Solution.java
Labels: 이분탐색

#85 solve: Programmers43238
  2. programmers/seung-hun/binary-search/PGMS43238.java
Labels: 이분탐색

#90 unsolve: BOJ 20164
  1.baekjoon/eonju/20164/Main.java
Labels: 구현

#91 solve: BOJ20164
  1.baekjoon/seung-hun/implementation/BOJ20164.java
Labels: 구현
