Repository ham-study/algorithm-study, pull requests merged in 2022-02, with the labels that each got.

#99 W5D4 -실패
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/example/Main2.java
  1.baekjoon/hanjo/boj/구현_S2_기차가어둠을헤치고/Main.java
  1.baekjoon/hanjo/boj/그래프_G5_숨바꼭질3/Main.java
  1.baekjoon/hanjo/programmers/이분탐색_3_입국심사/Solution.java
Labels: 그래프

#100 solve: BOJ13549
  1.baekjoon/seung-hun/graph/BOJ13549.java
Labels: 그래프

#101 sol: boj 10816
  1.baekjoon/jihun/boj_10816.java
Labels: 이분탐색

#102 solve: BOJ10816
  1.baekjoon/seung-hun/binary-search/BOJ10816.java
Labels: 이분탐색

#103 W5D5 - 성공
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/그래프_G5_숨바꼭질3/Main.java
  1.baekjoon/hanjo/boj/이분탐색_S4_숫자카드2/Main.java
  1.baekjoon/hanjo/programmers/자료구조_3_디스크컨트롤러/Solution.java
  1.baekjoon/hanjo/programmers/자료구조_3_디스크컨트롤러/solution.py
Labels: 이분탐색

#110 sol: boj 2573
  1.baekjoon/jihun/boj_2573.java
Labels: 구현

#109 solve: BOJ2573
  1.baekjoon/seung-hun/graph/BOJ2573.java
Labels: 그래프

#111 unsolve: Boj 2573
  1.baekjoon/eonju/2573/Main.java
Labels: 그래프

#113 W6D2 - 성공
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/이분탐색_S4_숫자카드2/Main.java
  1.baekjoon/hanjo/boj/정렬_G5_선긋기/Main.java
  1.baekjoon/hanjo/boj/정렬_G5_선긋기/testcase.txt
  1.baekjoon/hanjo/programmers/완전탐색_2_소수찾기/Solution.java
  1.baekjoon/hanjo/programmers/완전탐색_2_소수찾기/solution.py
Labels: 정렬

#114 solve: Boj 2170
  1.baekjoon/eonju/2170/Main.java
Labels: 정렬

#112 solve: BOJ2170
  1.baekjoon/seung-hun/sort/BOJ2170.java
Labels: 정렬

#118 W6D3 - 실패
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/동적계획법_G5_평범한배낭/Main.java
  1.baekjoon/hanjo/boj/정렬_G5_선긋기/Main.java
  1.baekjoon/hanjo/programmers/완전탐색_2_소수찾기/Solution.java
Labels: 동적계획법

#117 unsolve: Boj 12865
  1.baekjoon/eonju/12860/Main.java
Labels: 동적계획법

#115 unsolve: boj 12865
  1.baekjoon/jihun/boj_12865.java
Labels: 동적계획법

#116 solve: BOJ12865
  1.baekjoon/seung-hun/dp/BOJ12865.java
Labels: 동적계획법

#120 sol: boj 15886
  1.baekjoon/jihun/boj_15886.java
Labels: 구현

#121 W6D4 - 성공
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/구현_S2_내선물을받아줘2/Main.java
  1.baekjoon/hanjo/programmers/그래프탐색_2_타겟넘버/Solution.java
  1.baekjoon/hanjo/programmers/카카오_2_주차요금계산/Solution.java
Labels: 구현

#119 solve: BOJ 15886
  1.baekjoon/seung-hun/implementation/BOJ15886.java
Labels: 구현

#126 unsolve : BOJ 13164
  1.baekjoon/eonju/13164/Main.java
Labels: 탐욕법

#125 fail: BOJ13164
  1.baekjoon/seung-hun/greedy/BOJ13164.java
Labels: 탐욕법

#124 W6D5 - 실패
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/구현_S2_내선물을받아줘2/Main.java
  1.baekjoon/hanjo/boj/탐욕법_G5_행복유치원/Main.java
  1.baekjoon/hanjo/programmers/탐욕법_2_조이스틱/Solution.java
  1.baekjoon/hanjo/programmers/탐욕법_2_조이스틱/Test.java
  1.baekjoon/hanjo/programmers/탐욕법_2_조이스틱/Try1.java
  1.baekjoon/hanjo/programmers/탐욕법_2_조이스틱/solution.py
Labels: 탐욕법

#134 unsolve:BOJ2206
  1.baekjoon/eonju/13164/Main.java
  1.baekjoon/eonju/2206/Main.java
Labels: 그래프

#131 unsol: boj 2206
  1.baekjoon/jihun/boj_2206.java
Labels: 그래프

#133 solve: BOJ2206
  1.baekjoon/seung-hun/graph/BOJ2206.java
Labels: 그래프

#135 solve: BOJ21278
  1.baekjoon/seung-hun/bruteforce/BOJ21278.java
Labels: 그래프, 완전탐색

#136 unsolve : BOJ 21278
  1.baekjoon/eonju/11726/Main.java
  1.baekjoon/eonju/1260/Main.java
  1.baekjoon/eonju/1260/Node.java
  1.baekjoon/eonju/12919/Main.java
  1.baekjoon/eonju/15683/Main.java
  1.baekjoon/eonju/18352/Main.java
  1.baekjoon/eonju/2110/Main.java
  1.baekjoon/eonju/21278/Main.java
  1.baekjoon/eonju/2504/Main.java
  1.baekjoon/eonju/6443/Main.java
  1.baekjoon/eonju/9251/Main.java
  2. programmers/eonju/17680/Solution.java
  2. programmers/eonju/42626/Solution.java
  2. programmers/eonju/43162/Solution.java
  2. programmers/eonju/60059/Solution.java
Labels: 완전탐색

#138 부분성공 boj 21278
  1.baekjoon/jihun/boj_21278.java
Labels: 그래프

#137 W7D2 - 실패
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/최단경로_G5_호석이두마리치킨/Main.java
  1.baekjoon/hanjo/programmers/탐욕법_2_조이스틱/Answer.java
  1.baekjoon/hanjo/programmers/탐욕법_2_조이스틱/Solution.java
Labels: 그래프, 완전탐색

#139 unsol: programmers 64062
  2. programmers/jihun/programmers_64062.java
Labels: 이분탐색

#140 unsolve : PMS 64062
  2. programmers/eonju/64062/Solution.java
Labels: 이분탐색

#142 W7D3 - 실패
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/programmers/카카오_3_징검다리건너기/Solution.java
  1.baekjoon/hanjo/programmers/카카오_3_징검다리건너기/Try1.java
Labels: 이분탐색

#141 fail: PGMS64062
  2. programmers/seung-hun/binary-search/PGMS64062.java
Labels: 이분탐색

#143 unsol: programmers 64064
  2. programmers/jihun/programmers_64064.java
Labels: 구현

#144 unsolve : BOJ 64064
  2. programmers/eonju/64064/Solution.java
Labels: 구현

#146 sol: boj 1717
  1.baekjoon/jihun/boj_1717.java
Labels: 구현, 그래프

#147 unsolve : BOJ 1717
  1.baekjoon/eonju/1717/Main.java
  2. programmers/eonju/64064/Solution.java
Labels: 구현, 그래프

#148 W7D5 - 실패
  1.baekjoon/hanjo/boj/그래프_G4_집합의표현/Main.java
Labels: 구현, 그래프

#154 unsolve : BOJ 2961 메모리 초과
  1.baekjoon/eonju/2961/Main.java
Labels: 완전탐색

#155 W8D1 - 실패
  1.baekjoon/hanjo/algorithm/순열과조합/조합.java
  1.baekjoon/hanjo/algorithm/정렬/버블정렬.java
  1.baekjoon/hanjo/algorithm/정렬/삽입정렬.java
  1.baekjoon/hanjo/algorithm/정렬/선택정렬.java
  1.baekjoon/hanjo/algorithm/정렬/퀵정렬.java
  1.baekjoon/hanjo/algorithm/정렬/합병정렬.java
  1.baekjoon/hanjo/algorithm/정렬/합병정렬_심화.java
  1.baekjoon/hanjo/algorithm/정렬/힙정렬.java
  1.baekjoon/hanjo/boj/그래프_G4_집합의표현/Main.java
  1.baekjoon/hanjo/boj/완전탐색_S2_도영이가만든음식/Main.java
Labels: 완전탐색

#156 W8D2 - 성공
  1.baekjoon/hanjo/algorithm/정렬/삽입정렬.java
  1.baekjoon/hanjo/algorithm/정렬/퀵정렬.java
  1.baekjoon/hanjo/algorithm/정렬/합병정렬.java
  1.baekjoon/hanjo/algorithm/정렬/합병정렬_심화.java
  1.baekjoon/hanjo/algorithm/정렬/힙정렬.java
  1.baekjoon/hanjo/boj/최소비용_G4_네트워크연결/Main.java
  1.baekjoon/hanjo/boj/최소비용_G4_집합의표현/Main.java
Labels: 그래프

#157 unsolve : BOJ 1922
  1.baekjoon/eonju/1922/Main.java
Labels: 그래프

#158 W8D3
  1.baekjoon/hanjo/README.md
  1.baekjoon/hanjo/boj/스위핑_G3_수상택시/Main.java
  1.baekjoon/hanjo/boj/스위핑_G5_선긋기/Main.java
  1.baekjoon/hanjo/boj/스위핑_G5_선긋기/testcase.txt
  1.baekjoon/hanjo/boj/완전탐색_B2_일곱난쟁이/Main.java
Labels: 구현

#159 unsolve: BOJ 21315
  1.baekjoon/eonju/21315/Main.java
Labels: 완전탐색

#161 solve : BOJ 10026
  1.baekjoon/eonju/10026/Main.java
Labels: 그래프

#162 W8D5 - 성공
  1.baekjoon/hanjo/boj/그래프_S5_적록색약/Main.java
  1.baekjoon/hanjo/test/Test6.java
Labels: 그래프
